site_name: qiskit-mps-initializer

theme:
  name: "material"

nav:
  - Get Started:
      - Welcome: index.md
  - API:
      - Reference: api/reference.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
