site_name: qiskit-mps-initializer

theme:
  name: "material"

nav:
  - Get Started:
      - Welcome: index.md
  - API Reference:
      - Datatypes:
          - api/datatypes/quantum_state.md
          - api/datatypes/quantum_intensity.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
