[lint]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

pydocstyle.convention = "google"

[format]
# Enable auto-formatting of code examples in docstrings.
docstring-code-format = true